# Generated by Django 5.1.6 on 2025-02-28 20:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите наименование скидки', max_length=150, verbose_name='скидка')),
                ('discount_base', models.PositiveIntegerField(help_text='введите % скидки', verbose_name='скидка')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидка',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите наименование налога', max_length=150, verbose_name='налог')),
                ('tax_base', models.PositiveIntegerField(help_text='введите ставку налога в процентах', verbose_name='ставка')),
            ],
            options={
                'verbose_name': 'налог',
                'verbose_name_plural': 'налоги',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='ведите дату курса', verbose_name='дата')),
                ('code', models.CharField(help_text='ведите 3х-значный буквенный код', max_length=3, verbose_name='буквенный код')),
                ('name', models.CharField(max_length=150, verbose_name='полное название курса')),
                ('country', models.CharField(help_text='ведите страну валюты', max_length=150, verbose_name='страна валюты')),
                ('amount', models.FloatField(verbose_name='сумма')),
                ('related_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.currency', verbose_name='отношение текущего курса к другому')),
            ],
            options={
                'verbose_name': 'курс валюты',
                'verbose_name_plural': 'курсы валют',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите наименование', max_length=250, verbose_name='наименование')),
                ('description', models.TextField(blank=True, help_text='ведите описание', null=True, verbose_name='описание')),
                ('price', models.FloatField(help_text='введите цену', verbose_name='цена')),
                ('is_for_transaction', models.BooleanField(default=False, help_text='положить в корзину?', verbose_name='признак покупки')),
                ('currency', models.ForeignKey(blank=True, help_text='введите валюту', null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.currency', verbose_name='валюта')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_tag', models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный идентификатор сессии')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('currency_pay', models.ForeignKey(blank=True, help_text='введите валюту расчета', null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.currency', verbose_name='валюта расчета')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.discount', verbose_name='скидка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.item', verbose_name='товар')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.tax', verbose_name='налог')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
