# Generated by Django 5.1.6 on 2025-02-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_currency_related_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='date',
        ),
    ]
